from palette import alpha, bare, mix

BOXED = "0"
UNDERSCORE = "1"
WAVE = "2"
STRIKEOUT = "3"
BOLD_DOTTED = "5"

BOLD = "1"
ITALIC = "2"
BOLD_ITALIC = "3"


def style(foreground=None, background=None, font=None, effect=None, effect_type=None, stripe=None):
    value = {}
    if foreground:
        value["FOREGROUND"] = bare(foreground)
    if background:
        value["BACKGROUND"] = bare(background)
    if font:
        value["FONT_TYPE"] = font
    if effect:
        value["EFFECT_COLOR"] = bare(effect)
        value["EFFECT_TYPE"] = effect_type or WAVE
    if stripe:
        value["ERROR_STRIPE_COLOR"] = bare(stripe)
    return value


def colors(p):
    transparent = alpha(p["canvas"], 0.0)
    return {
        "ANNOTATIONS_COLOR": p["annotations"],
        "ADDED_LINES_COLOR": p["addedLine"],
        "MODIFIED_LINES_COLOR": p["modifiedLine"],
        "DELETED_LINES_COLOR": p["deletedLine"],
        "WHITESPACES_MODIFIED_LINES_COLOR": p["whitespaceModified"],
        "IGNORED_ADDED_LINES_BORDER_COLOR": mix(p["island"], p["addedLine"], 0.5),
        "IGNORED_MODIFIED_LINES_BORDER_COLOR": mix(p["island"], p["modifiedLine"], 0.5),
        "IGNORED_DELETED_LINES_BORDER_COLOR": mix(p["island"], p["deletedLine"], 0.5),
        "CARET_COLOR": p["cyan"],
        "CARET_ROW_COLOR": p["caretRow"],
        "CONSOLE_BACKGROUND_KEY": p["island"],
        "DOCUMENTATION_COLOR": p["docBg"],
        "GUTTER_BACKGROUND": p["island"],
        "INDENT_GUIDE": p["guide"],
        "SELECTED_INDENT_GUIDE": p["guideSelected"],
        "VISUAL_INDENT_GUIDE": p["guide"],
        "STRING_CONTENT_INDENT_GUIDE": mix(p["island"], p["green"], 0.4),
        "DOC_COMMENT_GUIDE": mix(p["island"], p["purple"], 0.35),
        "DOC_COMMENT_LINK": p["cyan"],
        "LINE_NUMBERS_COLOR": p["lineNumber"],
        "LINE_NUMBER_ON_CARET_ROW_COLOR": p["lineNumberActive"],
        "METHOD_SEPARATORS_COLOR": p["guide"],
        "RIGHT_MARGIN_COLOR": p["rightMargin"],
        "SELECTION_BACKGROUND": p["selection"],
        "SELECTION_BACKGROUND_INACTIVE": p["hover"],
        "SOFT_WRAP_SIGN_COLOR": p["lineNumber"],
        "TEARLINE_COLOR": p["guide"],
        "SELECTED_TEARLINE_COLOR": p["guideSelected"],
        "WHITESPACES": p["whitespace"],
        "FOLDED_TEXT_BORDER_COLOR": p["borderStrong"],
        "READONLY_FRAGMENT_BACKGROUND": p["stripe"],
        "RECENT_LOCATIONS_SELECTION": p["selection"],
        "LOOKUP_COLOR": p["docBg"],
        "NOTIFICATION_BACKGROUND": p["popup"],
        "MODIFIED_TAB_ICON": p["modifiedLine"],
        "RECURSIVE_CALL_ATTRIBUTES": mix(p["island"], p["gold"], 0.22),
        "DIFF_SEPARATOR_WAVE": p["borderStrong"],
        "GRID_STRIPE_COLOR": p["stripe"],
        "INLINE_REFACTORING_SETTINGS_DEFAULT": alpha(p["borderStrong"], 0.55),
        "INLINE_REFACTORING_SETTINGS_HOVERED": alpha(p["borderStrong"], 0.75),
        "INLINE_REFACTORING_SETTINGS_FOCUSED": alpha(p["magenta"], 0.75),
        "FILESTATUS_ADDED": p["green"],
        "FILESTATUS_COPIED": p["green"],
        "FILESTATUS_addedOutside": p["green"],
        "FILESTATUS_MODIFIED": p["cyan"],
        "FILESTATUS_modifiedOutside": p["cyan"],
        "FILESTATUS_NOT_CHANGED_IMMEDIATE": p["cyan"],
        "FILESTATUS_NOT_CHANGED_RECURSIVE": p["blue"],
        "FILESTATUS_DELETED": p["fgDisabled"],
        "FILESTATUS_IDEA_FILESTATUS_DELETED_FROM_FILE_SYSTEM": p["fgDisabled"],
        "FILESTATUS_IDEA_FILESTATUS_IGNORED": p["fgMuted"],
        "FILESTATUS_MERGED": p["purple"],
        "FILESTATUS_RENAMED": p["orange"],
        "FILESTATUS_UNKNOWN": p["warning"],
        "FILESTATUS_SWITCHED": p["magenta"],
        "FILESTATUS_OBSOLETE": p["fgDisabled"],
        "FILESTATUS_SUPPRESSED": p["fgDisabled"],
        "FILESTATUS_HIJACKED": p["orange"],
        "FILESTATUS_ERRORS": p["red"],
        "FILESTATUS_changelistConflict": p["red"],
        "FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_CONFLICTS": p["red"],
        "FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_BOTH_CONFLICTS": p["red"],
        "FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_PROPERTY_CONFLICTS": p["red"],
        "VCS_ANNOTATIONS_COLOR_1": mix(p["island"], p["cyan"], 0.14),
        "VCS_ANNOTATIONS_COLOR_2": mix(p["island"], p["green"], 0.14),
        "VCS_ANNOTATIONS_COLOR_3": mix(p["island"], p["purple"], 0.14),
        "VCS_ANNOTATIONS_COLOR_4": mix(p["island"], p["gold"], 0.14),
        "VCS_ANNOTATIONS_COLOR_5": mix(p["island"], p["magenta"], 0.14),
        "ScrollBar.background": transparent,
        "ScrollBar.trackColor": transparent,
        "ScrollBar.hoverTrackColor": transparent,
        "ScrollBar.thumbColor": p["scrollThumb"],
        "ScrollBar.thumbBorderColor": p["scrollThumb"],
        "ScrollBar.hoverThumbColor": p["scrollThumbHover"],
        "ScrollBar.hoverThumbBorderColor": p["scrollThumbHover"],
        "ScrollBar.Mac.trackColor": transparent,
        "ScrollBar.Mac.hoverTrackColor": transparent,
        "ScrollBar.Mac.thumbColor": p["scrollThumb"],
        "ScrollBar.Mac.thumbBorderColor": p["scrollThumb"],
        "ScrollBar.Mac.hoverThumbColor": p["scrollThumbHover"],
        "ScrollBar.Mac.hoverThumbBorderColor": p["scrollThumbHover"],
        "ScrollBar.Transparent.trackColor": transparent,
        "ScrollBar.Transparent.hoverTrackColor": transparent,
        "ScrollBar.Transparent.thumbColor": p["scrollThumb"],
        "ScrollBar.Transparent.thumbBorderColor": p["scrollThumb"],
        "ScrollBar.Transparent.hoverThumbColor": p["scrollThumbHover"],
        "ScrollBar.Transparent.hoverThumbBorderColor": p["scrollThumbHover"],
        "ScrollBar.Mac.Transparent.trackColor": transparent,
        "ScrollBar.Mac.Transparent.hoverTrackColor": transparent,
        "ScrollBar.Mac.Transparent.thumbColor": p["scrollThumb"],
        "ScrollBar.Mac.Transparent.thumbBorderColor": p["scrollThumb"],
        "ScrollBar.Mac.Transparent.hoverThumbColor": p["scrollThumbHover"],
        "ScrollBar.Mac.Transparent.hoverThumbBorderColor": p["scrollThumbHover"],
        "Scrollbar.Tabs.ThumbColor": p["scrollThumb"],
        "Scrollbar.Tabs.HoveredThumbColor": p["scrollThumbHover"],
        "Scrollbar.Tabs.TransparentThumbColor": alpha(p["borderStrong"], 0.0),
        "ActionButton.hoverBackground": p["hover"],
        "ActionButton.pressedBackground": p["selection"],
        "ActionButton.iconTextForeground": p["fg"],
        "Table.hoverBackground": p["hover"],
        "Bookmark.iconBackground": p["gold"],
        "Bookmark.Mnemonic.iconBackground": mix(p["island"], p["gold"], 0.28),
        "Bookmark.Mnemonic.iconBorderColor": p["gold"],
        "Bookmark.Mnemonic.iconForeground": p["fg"],
        "BLOCK_TERMINAL_BLOCK_BACKGROUND_START": mix(p["island"], p["fg"], 0.05),
        "BLOCK_TERMINAL_BLOCK_BACKGROUND_END": p["island"],
        "BLOCK_TERMINAL_HOVERED_BLOCK_BACKGROUND_START": alpha(p["fg"], 0.06),
        "BLOCK_TERMINAL_HOVERED_BLOCK_BACKGROUND_END": alpha(p["fg"], 0.02),
        "BLOCK_TERMINAL_SELECTED_BLOCK_BACKGROUND": p["selection"],
        "BLOCK_TERMINAL_SELECTED_BLOCK_STROKE_COLOR": p["magenta"],
        "BLOCK_TERMINAL_INACTIVE_SELECTED_BLOCK_BACKGROUND": p["hover"],
        "BLOCK_TERMINAL_INACTIVE_SELECTED_BLOCK_STROKE_COLOR": p["borderStrong"],
        "BLOCK_TERMINAL_ERROR_BLOCK_STROKE_COLOR": p["red"],
        "BLOCK_TERMINAL_PROMPT_SEPARATOR_COLOR": p["guide"],
        "BLOCK_TERMINAL_GENERATE_COMMAND_CARET_COLOR": p["purple"],
        "BLOCK_TERMINAL_GENERATE_COMMAND_PLACEHOLDER_FOREGROUND": mix(p["island"], p["purple"], 0.6),
    }


def block_terminal_ansi(p):
    return {
        "BLACK": p["consoleBlack"],
        "BLACK_BRIGHT": p["consoleDarkGray"],
        "RED": p["red"],
        "RED_BRIGHT": p["red"],
        "GREEN": p["green"],
        "GREEN_BRIGHT": p["green"],
        "YELLOW": p["gold"],
        "YELLOW_BRIGHT": p["gold"],
        "BLUE": p["blue"],
        "BLUE_BRIGHT": p["blue"],
        "MAGENTA": p["magenta"],
        "MAGENTA_BRIGHT": p["magenta"],
        "CYAN": p["cyan"],
        "CYAN_BRIGHT": p["cyan"],
        "WHITE": p["fgMuted"],
        "WHITE_BRIGHT": p["consoleWhite"],
    }


def console_ansi(p):
    return {
        "BLACK": p["consoleBlack"],
        "RED": p["red"],
        "GREEN": p["green"],
        "YELLOW": p["gold"],
        "BLUE": p["blue"],
        "MAGENTA": p["magenta"],
        "CYAN": p["cyan"],
        "GRAY": p["fgMuted"],
        "DARKGRAY": p["consoleDarkGray"],
        "RED_BRIGHT": p["red"],
        "GREEN_BRIGHT": p["green"],
        "YELLOW_BRIGHT": p["gold"],
        "BLUE_BRIGHT": p["blue"],
        "MAGENTA_BRIGHT": p["magenta"],
        "CYAN_BRIGHT": p["cyan"],
        "WHITE": p["consoleWhite"],
    }


def base_attributes(p):
    ansi = console_ansi(p)
    attributes = {
        "TEXT": style(p["fg"], p["island"]),
        "DEFAULT_KEYWORD": style(p["magenta"]),
        "DEFAULT_STRING": style(p["green"]),
        "DEFAULT_VALID_STRING_ESCAPE": style(p["orange"]),
        "DEFAULT_INVALID_STRING_ESCAPE": style(p["red"], effect=p["red"]),
        "DEFAULT_NUMBER": style(p["orange"]),
        "DEFAULT_LINE_COMMENT": style(p["fgMuted"], font=ITALIC),
        "DEFAULT_BLOCK_COMMENT": style(p["fgMuted"], font=ITALIC),
        "DEFAULT_DOC_COMMENT": style(p["fgMuted"], font=ITALIC),
        "DEFAULT_DOC_COMMENT_TAG": style(p["purple"], font=BOLD_ITALIC),
        "DEFAULT_DOC_COMMENT_TAG_VALUE": style(p["cyan"], font=ITALIC),
        "DEFAULT_DOC_MARKUP": style(p["fgMuted"]),
        "DEFAULT_OPERATION_SIGN": style(p["magenta"]),
        "DEFAULT_BRACES": style(p["fgPunct"]),
        "DEFAULT_BRACKETS": style(p["fgPunct"]),
        "DEFAULT_PARENTHS": style(p["fgPunct"]),
        "DEFAULT_DOT": style(p["fgPunct"]),
        "DEFAULT_COMMA": style(p["fgPunct"]),
        "DEFAULT_SEMICOLON": style(p["fgPunct"]),
        "DEFAULT_FUNCTION_DECLARATION": style(p["gold"]),
        "DEFAULT_FUNCTION_CALL": style(p["gold"]),
        "DEFAULT_INSTANCE_METHOD": style(p["gold"]),
        "DEFAULT_STATIC_METHOD": style(p["gold"]),
        "DEFAULT_CLASS_NAME": style(p["purple"]),
        "DEFAULT_CLASS_REFERENCE": style(p["purple"]),
        "DEFAULT_INTERFACE_NAME": style(p["purple"]),
        "DEFAULT_INSTANCE_FIELD": style(p["blue"]),
        "DEFAULT_STATIC_FIELD": style(p["blue"]),
        "DEFAULT_IDENTIFIER": style(p["cyan"]),
        "DEFAULT_LOCAL_VARIABLE": style(p["cyan"]),
        "DEFAULT_REASSIGNED_LOCAL_VARIABLE": style(p["cyan"]),
        "DEFAULT_GLOBAL_VARIABLE": style(p["cyan"]),
        "DEFAULT_PARAMETER": style(p["cyan"]),
        "DEFAULT_REASSIGNED_PARAMETER": style(p["cyan"]),
        "DEFAULT_CONSTANT": style(p["red"]),
        "DEFAULT_PREDEFINED_SYMBOL": style(p["gold"]),
        "DEFAULT_LABEL": style(p["magenta"]),
        "DEFAULT_METADATA": style(p["gold"]),
        "DEFAULT_TAG": style(p["magenta"]),
        "DEFAULT_ATTRIBUTE": style(p["gold"]),
        "DEFAULT_ENTITY": style(p["cyan"]),
        "DEFAULT_TEMPLATE_LANGUAGE_COLOR": style(p["magenta"]),
        "DEFAULT_HIGHLIGHTED_REFERENCE": style(background=mix(p["island"], p["cyan"], 0.16)),
        "INSTANCE_FIELD_ATTRIBUTES": style(p["blue"]),
        "STATIC_FIELD_ATTRIBUTES": style(p["blue"], font=ITALIC),
        "STATIC_FINAL_FIELD_ATTRIBUTES": style(p["blue"], font=ITALIC),
        "STATIC_METHOD_ATTRIBUTES": style(p["gold"], font=ITALIC),
        "TYPE_PARAMETER_NAME_ATTRIBUTES": style(p["purple"]),
        "ANNOTATION_NAME_ATTRIBUTES": style(p["gold"]),
        "ANNOTATION_ATTRIBUTE_NAME_ATTRIBUTES": style(p["gold"], font=ITALIC),
        "IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES": style(p["purple"]),
        "ERRORS_ATTRIBUTES": style(effect=p["red"], stripe=p["red"]),
        "WARNING_ATTRIBUTES": style(effect=p["warning"], stripe=p["warning"]),
        "INFO_ATTRIBUTES": style(effect=p["green"], stripe=p["green"]),
        "GENERIC_SERVER_ERROR_OR_WARNING": style(
            effect=p["warning"], effect_type=UNDERSCORE, stripe=p["warning"]
        ),
        "RUNTIME_ERROR": style(effect=p["red"], effect_type=BOLD_DOTTED, stripe=p["red"]),
        "DUPLICATE_FROM_SERVER": style(background=p["elevated"]),
        "WRONG_REFERENCES_ATTRIBUTES": style(p["red"], effect=p["red"], stripe=p["red"]),
        "BAD_CHARACTER": style(effect=p["red"], stripe=p["red"]),
        "TYPO": style(effect=p["green"]),
        "GRAMMAR_ERROR": style(effect=p["blue"]),
        "TEXT_STYLE_ERROR": style(effect=p["red"]),
        "TEXT_STYLE_WARNING": style(effect=p["warning"]),
        "TEXT_STYLE_SUGGESTION": style(effect=p["purple"]),
        "DEPRECATED_ATTRIBUTES": style(effect=p["fgMuted"], effect_type=STRIKEOUT),
        "MARKED_FOR_REMOVAL_ATTRIBUTES": style(effect=p["red"], effect_type=STRIKEOUT),
        "NOT_USED_ELEMENT_ATTRIBUTES": style(p["fgDisabled"], stripe=p["warning"]),
        "TODO_DEFAULT_ATTRIBUTES": style(p["goldText"], font=BOLD_ITALIC),
        "TODO_ATTRIBUTES": style(p["goldText"], font=BOLD_ITALIC, stripe=p["goldText"]),
        "BOOKMARKS_ATTRIBUTES": style(stripe=p["gold"]),
        "TEXT_SEARCH_RESULT_ATTRIBUTES": style(
            background=p["textSearchBg"], effect=p["goldText"], effect_type=BOXED
        ),
        "SEARCH_RESULT_ATTRIBUTES": style(background=p["searchBg"]),
        "WRITE_SEARCH_RESULT_ATTRIBUTES": style(background=p["writeSearchBg"]),
        "IDENTIFIER_UNDER_CARET_ATTRIBUTES": style(background=p["identifierBg"]),
        "WRITE_IDENTIFIER_UNDER_CARET_ATTRIBUTES": style(background=p["writeIdentifierBg"]),
        "MATCHED_BRACE_ATTRIBUTES": style(font=BOLD, effect=p["cyan"], effect_type=BOXED),
        "UNMATCHED_BRACE_ATTRIBUTES": style(effect=p["red"], effect_type=BOXED),
        "BLINKING_HIGHLIGHTS_ATTRIBUTES": style(effect=p["magenta"], effect_type=BOXED),
        "CTRL_CLICKABLE": style(p["cyan"], effect=p["cyan"], effect_type=UNDERSCORE),
        "HYPERLINK_ATTRIBUTES": style(p["cyan"], effect=p["cyan"], effect_type=UNDERSCORE),
        "FOLLOWED_HYPERLINK_ATTRIBUTES": style(p["purple"], effect=p["purple"], effect_type=UNDERSCORE),
        "INACTIVE_HYPERLINK_ATTRIBUTES": style(p["fgMuted"], effect=p["fgMuted"], effect_type=UNDERSCORE),
        "INJECTED_LANGUAGE_FRAGMENT": style(background=p["injectedBg"]),
        "FOLDED_TEXT_ATTRIBUTES": style(p["fgMuted"], p["foldedBg"]),
        "LIVE_TEMPLATE_ATTRIBUTES": style(effect=p["cyan"], effect_type=BOXED),
        "LIVE_TEMPLATE_INACTIVE_SEGMENT": style(effect=p["fgMuted"], effect_type=BOXED),
        "TEMPLATE_VARIABLE_ATTRIBUTES": style(p["purple"]),
        "CODE_LENS_BORDER_COLOR": style(effect=p["border"], effect_type=BOXED),
        "BREADCRUMBS_DEFAULT": style(p["fgMuted"]),
        "BREADCRUMBS_HOVERED": style(p["fg"], p["hover"]),
        "BREADCRUMBS_CURRENT": style(p["fg"], p["selection"]),
        "BREADCRUMBS_INACTIVE": style(p["fgDisabled"]),
        "INLINE_PARAMETER_HINT": style(p["fgMuted"], p["elevated"]),
        "INLINE_PARAMETER_HINT_CURRENT": style(p["fg"], p["selection"]),
        "INLINE_PARAMETER_HINT_HIGHLIGHTED": style(p["cyan"], p["elevated"]),
        "INLAY_DEFAULT": style(p["fgMuted"], p["elevated"]),
        "INLAY_TEXT_WITHOUT_BACKGROUND": style(p["fgMuted"]),
        "INLAY_BUTTON_DEFAULT": style(p["fgMuted"], effect=p["border"], effect_type=BOXED),
        "INLAY_BUTTON_HOVERED": style(p["fg"], effect=p["borderStrong"], effect_type=BOXED),
        "INLAY_BUTTON_FOCUSED": style(p["fg"], effect=p["magenta"], effect_type=BOXED),
        "INLAY_BUTTON_HINT": style(p["fgDisabled"]),
        "AI_INLAY_BUTTON_DEFAULT": style(p["fgMuted"], effect=p["purple"], effect_type=BOXED),
        "AI_INLAY_BUTTON_HOVERED": style(p["fg"], effect=p["purple"], effect_type=BOXED),
        "AI_INLAY_BUTTON_FOCUSED": style(p["fg"], effect=p["magenta"], effect_type=BOXED),
        "INLINE_SUGGESTION": style(p["fgDisabled"], font=ITALIC),
        "INLINE_PROMPT": style(p["purple"]),
        "INLINE_PROMPT_PROGRESS_DARK": style(p["purple"]),
        "INLINE_PROMPT_PROGRESS_LIGHT": style(p["magenta"]),
        "EXECUTIONPOINT_ATTRIBUTES": style(background=mix(p["island"], p["cyan"], 0.28)),
        "NOT_TOP_FRAME_ATTRIBUTES": style(background=mix(p["island"], p["cyan"], 0.14)),
        "BREAKPOINT_ATTRIBUTES": style(background=mix(p["island"], p["red"], 0.22), stripe=p["red"]),
        "EVALUATED_EXPRESSION_ATTRIBUTES": style(background=mix(p["island"], p["gold"], 0.2)),
        "EVALUATED_EXPRESSION_EXECUTION_LINE_ATTRIBUTES": style(
            background=mix(p["island"], p["gold"], 0.3)
        ),
        "DEBUGGER_INLINED_VALUES": style(p["fgMuted"], font=ITALIC),
        "DEBUGGER_INLINED_VALUES_MODIFIED": style(p["cyan"], font=ITALIC),
        "DEBUGGER_INLINED_VALUES_EXECUTION_LINE": style(p["gold"], font=ITALIC),
        "DEBUGGER_SMART_STEP_INTO_SELECTION": style(background=p["selection"]),
        "DEBUGGER_SMART_STEP_INTO_TARGET": style(background=mix(p["island"], p["cyan"], 0.2)),
        "INLINE_STACK_FRAMES": style(background=mix(p["island"], p["purple"], 0.2)),
        "LINE_FULL_COVERAGE": style(p["green"], font=BOLD),
        "LINE_PARTIAL_COVERAGE": style(p["gold"], font=BOLD),
        "LINE_NONE_COVERAGE": style(p["red"], font=BOLD),
        "RAINBOW_COLOR0": style(p["cyan"]),
        "RAINBOW_COLOR1": style(p["green"]),
        "RAINBOW_COLOR2": style(p["gold"]),
        "RAINBOW_COLOR3": style(p["magenta"]),
        "RAINBOW_COLOR4": style(p["blue"]),
        "LOG_ERROR_OUTPUT": style(p["red"]),
        "LOG_WARNING_OUTPUT": style(p["warning"]),
        "LOG_INFO_OUTPUT": style(p["green"]),
        "LOG_DEBUG_OUTPUT": style(p["cyan"]),
        "LOG_VERBOSE_OUTPUT": style(p["fgMuted"]),
        "LOG_EXPIRED_ENTRY": style(p["fgDisabled"]),
        "CONSOLE_NORMAL_OUTPUT": style(p["fg"]),
        "CONSOLE_ERROR_OUTPUT": style(p["red"]),
        "CONSOLE_USER_INPUT": style(p["green"]),
        "CONSOLE_SYSTEM_OUTPUT": style(p["fg"]),
        "DIFF_INSERTED": style(background=p["diffInserted"]),
        "DIFF_DELETED": style(background=p["diffDeleted"]),
        "DIFF_MODIFIED": style(background=p["diffModified"]),
        "DIFF_CONFLICT": style(background=p["diffConflict"]),
        "DIFF_ABSENT": style(background=p["stripe"]),
        "DIFF_UNKNOWN": style(background=p["elevated"]),
        "DIFF_DELETED_FROM_FS": style(p["fgDisabled"], p["diffDeleted"]),
        "DELETED_TEXT_ATTRIBUTES": style(
            p["fgMuted"], p["diffDeleted"], effect=p["fgMuted"], effect_type=STRIKEOUT
        ),
        "TERMINAL_COMMAND_TO_RUN_USING_IDE": style(background=mix(p["island"], p["green"], 0.22)),
        "TERMINAL_CLASS_NAME_LOG_REFERENCE": style(p["cyan"], effect=p["cyan"], effect_type=UNDERSCORE),
        "BLOCK_TERMINAL_COMMAND": style(p["fg"], font=BOLD),
        "BLOCK_TERMINAL_SEARCH_ENTRY": style(background=p["textSearchBg"]),
        "BLOCK_TERMINAL_CURRENT_SEARCH_ENTRY": style(background=p["writeSearchBg"]),
        "BLOCK_TERMINAL_GENERATE_COMMAND_PROMPT_TEXT": style(p["purple"]),
    }
    for name, color in ansi.items():
        attributes[f"CONSOLE_{name}_OUTPUT"] = style(color)
    for name, color in block_terminal_ansi(p).items():
        attributes[f"BLOCK_TERMINAL_{name}"] = style(color)
    attributes.update(
        {
            "NEXT_EDIT.DIFF_ADD_BACKGROUND": style(background=p["diffInserted"]),
            "NEXT_EDIT.DIFF_AFTER_BACKGROUND": style(background=p["stripe"]),
            "NEXT_EDIT.DIFF_PANEL_BORDER": style(effect=p["purple"], effect_type=BOXED),
            "NEXT_EDIT.REMOVAL_BACKGROUND": style(background=p["diffDeleted"]),
            "NEXT_EDIT.EDIT_RANGE.LINE_BACKGROUND": style(
                background=mix(p["island"], p["purple"], 0.12)
            ),
            "NEXT_EDIT.EDIT_RANGE.GUTTER_BACKGROUND": style(
                background=mix(p["island"], p["purple"], 0.3)
            ),
            "NEXT_EDIT.INSIGHT_BACKGROUND": style(background=mix(p["island"], p["purple"], 0.16)),
            "NEXT_EDIT.REVIEW_HINT.BACKGROUND": style(background=p["elevated"]),
        }
    )
    custom = {
        "CUSTOM_KEYWORD1_ATTRIBUTES": p["magenta"],
        "CUSTOM_KEYWORD2_ATTRIBUTES": p["cyan"],
        "CUSTOM_KEYWORD3_ATTRIBUTES": p["purple"],
        "CUSTOM_KEYWORD4_ATTRIBUTES": p["gold"],
        "CUSTOM_STRING_ATTRIBUTES": p["green"],
        "CUSTOM_NUMBER_ATTRIBUTES": p["orange"],
        "CUSTOM_VALID_STRING_ESCAPE_ATTRIBUTES": p["orange"],
    }
    for name, color in custom.items():
        attributes[name] = style(color)
    attributes["CUSTOM_LINE_COMMENT_ATTRIBUTES"] = style(p["fgMuted"], font=ITALIC)
    attributes["CUSTOM_MULTI_LINE_COMMENT_ATTRIBUTES"] = style(p["fgMuted"], font=ITALIC)
    attributes["CUSTOM_INVALID_STRING_ESCAPE_ATTRIBUTES"] = style(p["red"], effect=p["red"])
    return attributes


def go_attributes(p):
    return {
        "GO_KEYWORD": style(p["magenta"]),
        "GO_BUILTIN_CONSTANT": style(p["red"]),
        "GO_BUILTIN_VARIABLE": style(p["red"]),
        "GO_BUILTIN_FUNCTION": style(p["gold"]),
        "GO_BUILTIN_FUNCTION_CALL": style(p["gold"]),
        "GO_BUILTIN_TYPE_REFERENCE": style(p["magenta"]),
        "GO_TYPE_REFERENCE": style(p["purple"]),
        "GO_TYPE_SPECIFICATION": style(p["purple"]),
        "GO_TYPE_PARAMETER": style(p["purple"]),
        "GO_PACKAGE_EXPORTED_STRUCT": style(p["purple"]),
        "GO_PACKAGE_LOCAL_STRUCT": style(p["purple"]),
        "GO_EXPORTED_STRUCT_REFERENCE": style(p["purple"]),
        "GO_LOCAL_STRUCT_REFERENCE": style(p["purple"]),
        "GO_PACKAGE_EXPORTED_INTERFACE": style(p["cyan"], font=ITALIC),
        "GO_PACKAGE_LOCAL_INTERFACE": style(p["cyan"], font=ITALIC),
        "GO_EXPORTED_INTERFACE_REFERENCE": style(p["cyan"], font=ITALIC),
        "GO_LOCAL_INTERFACE_REFERENCE": style(p["cyan"], font=ITALIC),
        "GO_EXPORTED_FUNCTION": style(p["gold"]),
        "GO_EXPORTED_FUNCTION_CALL": style(p["gold"]),
        "GO_LOCAL_FUNCTION": style(p["gold"]),
        "GO_LOCAL_FUNCTION_CALL": style(p["gold"]),
        "GO_FUNCTION_PARAMETER": style(p["cyan"]),
        "GO_METHOD_RECEIVER": style(p["cyan"]),
        "GO_LOCAL_VARIABLE": style(p["cyan"]),
        "GO_LOCAL_VARIABLE_CALL": style(p["cyan"]),
        "GO_SCOPE_VARIABLE": style(p["cyan"]),
        "GO_SHADOWING_VARIABLE": style(p["cyan"], effect=p["warning"], effect_type=BOLD_DOTTED),
        "GO_REASSIGNMENT_IN_SHORT_VAR_DECLARATION": style(p["cyan"], font=ITALIC),
        "GO_PACKAGE_EXPORTED_VARIABLE": style(p["cyan"]),
        "GO_PACKAGE_EXPORTED_VARIABLE_CALL": style(p["cyan"]),
        "GO_PACKAGE_LOCAL_VARIABLE": style(p["cyan"]),
        "GO_PACKAGE_LOCAL_VARIABLE_CALL": style(p["cyan"]),
        "GO_LOCAL_CONSTANT": style(p["red"]),
        "GO_PACKAGE_EXPORTED_CONSTANT": style(p["red"]),
        "GO_PACKAGE_LOCAL_CONSTANT": style(p["red"]),
        "GO_STRUCT_EXPORTED_MEMBER": style(p["blue"]),
        "GO_STRUCT_EXPORTED_MEMBER_CALL": style(p["blue"]),
        "GO_STRUCT_LOCAL_MEMBER": style(p["blue"]),
        "GO_STRUCT_LOCAL_MEMBER_CALL": style(p["blue"]),
        "GO_PACKAGE": style(p["fg"]),
        "GO_LABEL": style(p["magenta"]),
        "GO_STRING_FORMAT_SPECIFIER": style(p["orange"]),
        "GO_TAG_KEY": style(p["gold"], font=BOLD),
        "GO_TAG_VALUE": style(p["green"]),
        "GO_TAG_TEXT": style(p["green"]),
        "GO_TAG_COLON": style(p["fgPunct"]),
        "GO_BUILD_TAG": style(p["magenta"], font=BOLD),
        "GO_BUILD_OPERATOR": style(p["orange"]),
        "GO_BUILD_PAREN": style(p["fgPunct"]),
        "GO_COMMENT_REFERENCE": style(p["cyan"], font=ITALIC),
        "GO_COMMENT_KEYWORD": style(p["purple"], font=BOLD_ITALIC),
        "GO_SYNTAX_UPDATE": style(effect=p["purple"], effect_type=BOLD_DOTTED, stripe=p["purple"]),
        "GO_BAD_TOKEN": style(p["red"], effect=p["red"]),
        "GO_TEMPLATE_KEYWORD": style(p["magenta"]),
        "GO_TEMPLATE_VARIABLE": style(p["cyan"]),
        "GO_TEMPLATE_COMMENT": style(p["fgMuted"], font=ITALIC),
        "GO_TEMPLATE_BAD_TOKEN": style(p["red"], effect=p["red"]),
    }


def language_attributes(p):
    attributes = {
        "YAML_SCALAR_KEY": style(p["cyan"]),
        "YAML_SCALAR_VALUE": style(p["fg"]),
        "YAML_SCALAR_STRING": style(p["green"]),
        "YAML_SCALAR_DSTRING": style(p["green"]),
        "YAML_SCALAR_LIST": style(p["green"]),
        "YAML_TEXT": style(p["fg"]),
        "YAML_COMMENT": style(p["fgMuted"], font=ITALIC),
        "YAML_SIGN": style(p["magenta"]),
        "YAML_ANCHOR": style(p["purple"], font=BOLD),
        "JSON_PROPERTY_KEY": style(p["cyan"]),
        "JSON_KEYWORD": style(p["magenta"]),
        "JSON_NUMBER": style(p["orange"]),
        "JSON_STRING": style(p["green"]),
        "JSON_LINE_COMMENT": style(p["fgMuted"], font=ITALIC),
        "JSON_BLOCK_COMMENT": style(p["fgMuted"], font=ITALIC),
        "JSON_BRACES": style(p["fgPunct"]),
        "JSON_BRACKETS": style(p["fgPunct"]),
        "JSON_COMMA": style(p["fgPunct"]),
        "JSON_COLON": style(p["fgPunct"]),
        "JSON_VALID_ESCAPE": style(p["orange"]),
        "JSON_INVALID_ESCAPE": style(p["red"], effect=p["red"]),
        "JSON_PARAMETER": style(p["cyan"]),
        "JSON_IDENTIFIER": style(p["fg"]),
        "MARKDOWN_TEXT": style(p["fg"]),
        "MARKDOWN_HEADER": style(p["magenta"], font=BOLD),
        "MARKDOWN_HEADER_BOLD": style(p["magenta"], font=BOLD),
        "MARKDOWN_HEADER_MARKER": style(p["fgMuted"]),
        "MARKDOWN_BOLD": style(p["fg"], font=BOLD),
        "MARKDOWN_BOLD_MARKER": style(p["fgMuted"]),
        "MARKDOWN_ITALIC": style(p["fg"], font=ITALIC),
        "MARKDOWN_ITALIC_MARKER": style(p["fgMuted"]),
        "MARKDOWN_STRIKE_THROUGH": style(p["fgMuted"], effect=p["fgMuted"], effect_type=STRIKEOUT),
        "MARKDOWN_CODE_SPAN": style(p["green"]),
        "MARKDOWN_CODE_SPAN_MARKER": style(p["fgMuted"]),
        "MARKDOWN_CODE_BLOCK": style(p["green"]),
        "MARKDOWN_CODE_FENCE": style(p["green"]),
        "MARKDOWN_CODE_FENCE_MARKER": style(p["fgMuted"]),
        "MARKDOWN_CODE_FENCE_LANGUAGE": style(p["purple"], font=ITALIC),
        "MARKDOWN_LINK_TEXT": style(p["cyan"]),
        "MARKDOWN_LINK_LABEL": style(p["cyan"]),
        "MARKDOWN_LINK_DESTINATION": style(p["cyan"], effect=p["cyan"], effect_type=UNDERSCORE),
        "MARKDOWN_LINK_TITLE": style(p["gold"]),
        "MARKDOWN_LINK_DEFINITION": style(p["cyan"]),
        "MARKDOWN_AUTO_LINK": style(p["cyan"], effect=p["cyan"], effect_type=UNDERSCORE),
        "MARKDOWN_EXPLICIT_LINK": style(p["cyan"]),
        "MARKDOWN_REFERENCE_LINK": style(p["cyan"]),
        "MARKDOWN_IMAGE": style(p["purple"]),
        "MARKDOWN_LIST_MARKER": style(p["magenta"]),
        "MARKDOWN_UNORDERED_LIST": style(p["fg"]),
        "MARKDOWN_ORDERED_LIST": style(p["fg"]),
        "MARKDOWN_LIST_ITEM": style(p["fg"]),
        "MARKDOWN_BLOCK_QUOTE": style(p["fgMuted"], font=ITALIC),
        "MARKDOWN_BLOCK_QUOTE_MARKER": style(p["magenta"]),
        "MARKDOWN_HRULE": style(p["fgMuted"]),
        "MARKDOWN_TABLE_SEPARATOR": style(p["fgPunct"]),
        "MARKDOWN_COMMENT": style(p["fgMuted"], font=ITALIC),
        "MARKDOWN_INLINE_HTML": style(p["fgMuted"]),
        "MARKDOWN_HTML_BLOCK": style(p["fgMuted"]),
        "MARKDOWN_FRONT_MATTER_HEADER_DELIMITER": style(p["fgMuted"]),
        "MARKDOWN_ALERT_TITLE_NOTE": style(p["cyan"], font=BOLD),
        "MARKDOWN_ALERT_TITLE_TIP": style(p["green"], font=BOLD),
        "MARKDOWN_ALERT_TITLE_IMPORTANT": style(p["purple"], font=BOLD),
        "MARKDOWN_ALERT_TITLE_WARNING": style(p["warning"], font=BOLD),
        "MARKDOWN_ALERT_TITLE_CAUTION": style(p["red"], font=BOLD),
        "HCL_BLOCK_ONLY_NAME_KEY": style(p["magenta"], font=BOLD),
        "HCL_BLOCK_FIRST_TYPE_KEY": style(p["magenta"], font=BOLD),
        "HCL_BLOCK_SECOND_TYPE_KEY": style(p["purple"]),
        "HCL_BLOCK_OTHER_TYPES_KEY": style(p["gold"]),
        "HCL_BLOCK_NAME_KEY": style(p["gold"]),
        "HCL_PROPERTY_KEY": style(p["cyan"]),
        "HCL_IDENTIFIER": style(p["fg"]),
        "HCL_KEYWORD": style(p["magenta"]),
        "HCL_STRING": style(p["green"]),
        "HCL_NUMBER": style(p["orange"]),
        "HCL_LINE_COMMENT": style(p["fgMuted"], font=ITALIC),
        "HCL_BLOCK_COMMENT": style(p["fgMuted"], font=ITALIC),
        "HCL_BRACES": style(p["fgPunct"]),
        "HCL_BRACKETS": style(p["fgPunct"]),
        "HCL_COMMA": style(p["fgPunct"]),
        "HCL_OPERATION_SIGN": style(p["magenta"]),
        "HCL_VALID_ESCAPE": style(p["orange"]),
        "HCL_INVALID_ESCAPE": style(p["red"], effect=p["red"]),
        "HTTP_REQUEST_PARAMETER_NAME": style(p["cyan"]),
        "HTTP_REQUEST_PARAMETER_VALUE": style(p["green"]),
        "COMPOSE_SERVICE_STATUS_SUCCESS": style(p["green"]),
        "COMPOSE_SERVICE_STATUS_ERROR": style(p["red"]),
        "COMPOSE_SERVICE_STATUS_NEUTRAL": style(p["fgMuted"]),
        "KUBERNETES_POD_STATUS_SUCCESS": style(p["green"]),
        "KUBERNETES_POD_STATUS_ERROR": style(p["red"]),
        "KUBERNETES_POD_STATUS_OTHER": style(p["fgMuted"]),
        "SQL_OUTER_QUERY_COLUMN": style(p["cyan"], font=ITALIC),
        "SQL_SYNTHETIC_ENTITY": style(p["purple"], font=ITALIC),
        "XML_TAG": style(p["fgPunct"]),
        "XML_TAG_NAME": style(p["magenta"]),
        "XML_TAG_DATA": style(p["fg"]),
        "XML_ATTRIBUTE_NAME": style(p["gold"]),
        "XML_ENTITY_REFERENCE": style(p["cyan"]),
        "XML_PROLOGUE": style(p["fgMuted"]),
        "HTML_TAG": style(p["fgPunct"]),
        "HTML_TAG_NAME": style(p["magenta"]),
        "HTML_ATTRIBUTE_NAME": style(p["gold"]),
        "HTML_ATTRIBUTE_VALUE": style(p["green"]),
        "HTML_ENTITY_REFERENCE": style(p["cyan"]),
        "CSS.COLOR": style(p["orange"]),
        "CSS.IMPORTANT": style(p["red"], font=BOLD),
        "CSS.URL": style(p["cyan"]),
        "REGEXP.BRACES": style(p["fgPunct"]),
        "REGEXP.BRACKETS": style(p["fgPunct"]),
        "REGEXP.PARENTHS": style(p["fgPunct"]),
        "REGEXP.META": style(p["magenta"]),
        "REGEXP.CHAR_CLASS": style(p["purple"]),
        "REGEXP.ESC_CHARACTER": style(p["orange"]),
        "REGEXP.QUOTE_CHARACTER": style(p["orange"]),
        "REGEXP.REDUNDANT_ESCAPE": style(p["warning"], effect=p["warning"]),
        "REGEXP_MATCHED_GROUPS": style(background=p["searchBg"]),
        "PROPERTIES.KEY": style(p["cyan"]),
        "PROPERTIES.KEY_VALUE_SEPARATOR": style(p["fgPunct"]),
        "PROPERTIES.VALID_STRING_ESCAPE": style(p["orange"]),
        "PROPERTIES.INVALID_STRING_ESCAPE": style(p["red"], effect=p["red"]),
        "JS.GLOBAL_VARIABLE": style(p["cyan"], font=ITALIC),
        "JS.GLOBAL_FUNCTION": style(p["gold"], font=ITALIC),
        "JS.LOCAL_VARIABLE": style(p["cyan"]),
        "JS.INSTANCE_MEMBER_FUNCTION": style(p["gold"]),
        "JS.REGEXP": style(p["orange"]),
        "TS.TYPE_PARAMETER": style(p["purple"]),
        "TS.TYPE_GUARD": style(p["purple"], font=ITALIC),
    }
    proto = {
        "PROTO_KEYWORD": style(p["magenta"]),
        "PROTO_MESSAGE": style(p["purple"]),
        "PROTO_SERVICE": style(p["purple"], font=BOLD),
        "PROTO_ENUM": style(p["purple"]),
        "PROTO_ENUM_VALUE": style(p["red"]),
        "PROTO_EXTEND": style(p["purple"]),
        "PROTO_ONEOF": style(p["magenta"]),
        "PROTO_IDENTIFIER": style(p["fg"]),
        "PROTO_NUMBER": style(p["orange"]),
        "PROTO_STRING": style(p["green"]),
        "PROTO_LINE_COMMENT": style(p["fgMuted"], font=ITALIC),
        "PROTO_BLOCK_COMMENT": style(p["fgMuted"], font=ITALIC),
        "PROTO_BRACES": style(p["fgPunct"]),
        "PROTO_BRACKETS": style(p["fgPunct"]),
        "PROTO_PARENTHESES": style(p["fgPunct"]),
        "PROTO_COMMA": style(p["fgPunct"]),
        "PROTO_DOT": style(p["fgPunct"]),
        "PROTO_SEMICOLON": style(p["fgPunct"]),
        "PROTO_OPERATION_SIGN": style(p["magenta"]),
        "PROTO_VALID_STRING_ESCAPE": style(p["orange"]),
        "PROTO_INVALID_STRING_ESCAPE": style(p["red"], effect=p["red"]),
        "PROTO_BAD_CHARACTER": style(p["red"], effect=p["red"]),
    }
    attributes.update(proto)
    terraform_identifiers = {
        "HCL_RESOURCE_IDENTIFIER": p["purple"],
        "HCL_DATASOURCE_IDENTIFIER": p["purple"],
        "HCL_EPHEMERAL_IDENTIFIER": p["purple"],
        "HCL_VARIABLE_IDENTIFIER": p["cyan"],
        "HCL_VARIABLES_IDENTIFIER": p["cyan"],
        "HCL_VAR_IDENTIFIER": p["cyan"],
        "HCL_LOCAL_IDENTIFIER": p["blue"],
        "HCL_LOCALS_IDENTIFIER": p["blue"],
        "HCL_MODULE_IDENTIFIER": p["gold"],
        "HCL_OUTPUT_IDENTIFIER": p["gold"],
        "HCL_PROVIDER_IDENTIFIER": p["magenta"],
        "HCL_PROVIDERS_IDENTIFIER": p["magenta"],
        "HCL_TERRAFORM_IDENTIFIER": p["magenta"],
        "HCL_BACKEND_IDENTIFIER": p["magenta"],
        "HCL_PATH_IDENTIFIER": p["cyan"],
        "HCL_SELF_IDENTIFIER": p["red"],
        "HCL_COUNT_IDENTIFIER": p["red"],
        "HCL_FOR_EACH_IDENTIFIER": p["red"],
        "HCL_DEPENDS_ON_IDENTIFIER": p["orange"],
        "HCL_LIFECYCLE_IDENTIFIER": p["orange"],
        "HCL_DYNAMIC_BLOCK_IDENTIFIER": p["orange"],
        "HCL_DYNAMIC_BLOCK_CONTENT_IDENTIFIER": p["orange"],
        "HCL_MOVED_BLOCK_IDENTIFIER": p["orange"],
        "HCL_REMOVED_BLOCK_IDENTIFIER": p["orange"],
        "HCL_IMPORT_IDENTIFIER": p["orange"],
        "HCL_CHECK_BLOCK_IDENTIFIER": p["green"],
        "HCL_ASSERT_BLOCK_IDENTIFIER": p["green"],
        "HCL_PRECONDITION_BLOCK_IDENTIFIER": p["green"],
        "HCL_POSTCONDITION_BLOCK_IDENTIFIER": p["green"],
        "HCL_CONDITION_IDENTIFIER": p["green"],
        "HCL_VALIDATION_IDENTIFIER": p["green"],
        "HCL_ERROR_MESSAGE_IDENTIFIER": p["red"],
        "HCL_TEST_IDENTIFIER": p["green"],
        "HCL_RUN_IDENTIFIER": p["green"],
        "HCL_MOCK_PROVIDER_IDENTIFIER": p["warning"],
        "HCL_MOCK_RESOURCE_IDENTIFIER": p["warning"],
        "HCL_MOCK_DATA_IDENTIFIER": p["warning"],
        "HCL_OVERRIDE_RESOURCE_IDENTIFIER": p["warning"],
        "HCL_OVERRIDE_DATA_IDENTIFIER": p["warning"],
        "HCL_OVERRIDE_MODULE_IDENTIFIER": p["warning"],
    }
    for name, color in terraform_identifiers.items():
        attributes[name] = style(color)
    return attributes


def ai_lens_attributes(p, editor_background=None):
    background = editor_background or p["island"]
    tint = 0.10 if p["dark"] else 0.07
    return {
        "NOVA_AI_UNREVIEWED": style(background=mix(background, p["magenta"], tint), stripe=p["magenta"]),
        "NOVA_AI_REVIEWED": style(stripe=mix(background, p["cyan"], 0.6)),
        "NOVA_AI_COMMITTED": style(stripe=mix(background, p["purple"], 0.75)),
    }


def attributes(p):
    merged = base_attributes(p)
    merged.update(go_attributes(p))
    merged.update(language_attributes(p))
    merged.update(ai_lens_attributes(p))
    return merged
